name: "FirstTry Gate"
description: "Run FirstTry local gate (ruff/black/mypy/pytest/coverage + optional license)"
inputs:
  gate:
    description: "Gate to run (pre-commit or pre-push)"
    default: "pre-commit"
  require-license:
    description: "Require license check (true/false)"
    default: "false"
  license-key:
    description: "FIRSTTRY_LICENSE_KEY"
    required: false
  license-url:
    description: "FIRSTTRY_LICENSE_URL"
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        python -m pip install -U pip
        pip install ruff black mypy pytest coverage click rich PyYAML
        pip install -e tools/firsttry
    - shell: bash
      env:
        FIRSTTRY_LICENSE_KEY: ${{ inputs.license-key }}
        FIRSTTRY_LICENSE_URL: ${{ inputs.license-url }}
      run: |
        set -e
        if [[ "${{ inputs.require-license }}" == "true" ]]; then
          python -m firsttry run --gate "${{ inputs.gate }}" --require-license
        else
          python -m firsttry run --gate "${{ inputs.gate }}"
        fi
