name: ci-gate

on:
  push:
    paths:
      - "**/*.py"
      - ".github/workflows/ci-gate.yml"
      - "pyproject.toml"
      - "pytest.ini"
      - "Makefile"
      - "tools/firsttry/**"
  pull_request:
    paths:
      - "**/*.py"
      - ".github/workflows/ci-gate.yml"
      - "pyproject.toml"
      - "pytest.ini"
      - "Makefile"
      - "tools/firsttry/**"

permissions:
  contents: read

concurrency:
  group: ci-gate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-gate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project + dev dependencies
        run: |
          python -m pip install --upgrade pip

          # Prefer editable install with dev extras; fall back to a non-editable install
          python -m pip install -e ".[dev]" || python -m pip install ".[dev]"

          # If present, install pinned dev tool versions to avoid surprises from
          # floating dev-dependency versions. This file is created/committed by
          # contributors to lock the toolchain used in CI.
          if [ -f requirements-dev.txt ]; then
            python -m pip install -r requirements-dev.txt
          fi

          # install the FirstTry CLI/tooling package (tools/firsttry) so tests can `import firsttry.*`
          if [ -d "tools/firsttry" ]; then
            python -m pip install -e tools/firsttry
          fi

      - name: Run tests with coverage
        run: |
          coverage run --rcfile=.coveragerc -m pytest -q
          coverage xml --rcfile=.coveragerc
          coverage report -m --rcfile=.coveragerc

      - name: Enforce temporary relaxed coverage gate (55%)
        run: |
            python - << 'PY'
            import sys, xml.etree.ElementTree as ET
            tree = ET.parse("coverage.xml")
            total = tree.getroot().attrib.get("line-rate")
            if total is None:
                print("ERROR: no line-rate in coverage.xml")
                sys.exit(1)
            pct = float(total) * 100.0
            print(f"Total coverage: {pct:.2f}%")
            THRESH = 80.0
            if pct < THRESH:
                print(f"::error ::Coverage {pct:.2f}% is below {THRESH}% threshold")
                sys.exit(1)
            PY
